# Generated by Django 4.1.6 on 2023-04-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegAccont',
            new_name='RegAccount',
        ),
    ]
