# Generated by Django 4.1.6 on 2023-04-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_regaccont_regaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='regaccount',
            name='email',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
